/**
 *
 *  UserInfo.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace domain_new
{

class UserInfo
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _email;
        static const std::string _avatar;
        static const std::string _create_ts;
        static const std::string _update_ts;
        static const std::string _login_source;
        static const std::string _wallet_token;
        static const std::string _banner_img;
        static const std::string _introduction;
        static const std::string _website;
        static const std::string _twitter;
        static const std::string _telegram;
        static const std::string _nick_name;
        static const std::string _referrer_uid;
        static const std::string _wallet_address;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit UserInfo(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit UserInfo(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    UserInfo(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    UserInfo() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column email  */
    ///Get the value of the column email, returns the default value if the column is null
    const std::string &getValueOfEmail() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEmail() const noexcept;
    ///Set the value of the column email
    void setEmail(const std::string &pEmail) noexcept;
    void setEmail(std::string &&pEmail) noexcept;
    void setEmailToNull() noexcept;

    /**  For column avatar  */
    ///Get the value of the column avatar, returns the default value if the column is null
    const std::string &getValueOfAvatar() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAvatar() const noexcept;
    ///Set the value of the column avatar
    void setAvatar(const std::string &pAvatar) noexcept;
    void setAvatar(std::string &&pAvatar) noexcept;
    void setAvatarToNull() noexcept;

    /**  For column create_ts  */
    ///Get the value of the column create_ts, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreateTs() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreateTs() const noexcept;
    ///Set the value of the column create_ts
    void setCreateTs(const ::trantor::Date &pCreateTs) noexcept;
    void setCreateTsToNull() noexcept;

    /**  For column update_ts  */
    ///Get the value of the column update_ts, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdateTs() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdateTs() const noexcept;
    ///Set the value of the column update_ts
    void setUpdateTs(const ::trantor::Date &pUpdateTs) noexcept;
    void setUpdateTsToNull() noexcept;

    /**  For column login_source  */
    ///Get the value of the column login_source, returns the default value if the column is null
    const std::string &getValueOfLoginSource() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLoginSource() const noexcept;
    ///Set the value of the column login_source
    void setLoginSource(const std::string &pLoginSource) noexcept;
    void setLoginSource(std::string &&pLoginSource) noexcept;

    /**  For column wallet_token  */
    ///Get the value of the column wallet_token, returns the default value if the column is null
    const std::string &getValueOfWalletToken() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getWalletToken() const noexcept;
    ///Set the value of the column wallet_token
    void setWalletToken(const std::string &pWalletToken) noexcept;
    void setWalletToken(std::string &&pWalletToken) noexcept;
    void setWalletTokenToNull() noexcept;

    /**  For column banner_img  */
    ///Get the value of the column banner_img, returns the default value if the column is null
    const std::string &getValueOfBannerImg() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBannerImg() const noexcept;
    ///Set the value of the column banner_img
    void setBannerImg(const std::string &pBannerImg) noexcept;
    void setBannerImg(std::string &&pBannerImg) noexcept;
    void setBannerImgToNull() noexcept;

    /**  For column introduction  */
    ///Get the value of the column introduction, returns the default value if the column is null
    const std::string &getValueOfIntroduction() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getIntroduction() const noexcept;
    ///Set the value of the column introduction
    void setIntroduction(const std::string &pIntroduction) noexcept;
    void setIntroduction(std::string &&pIntroduction) noexcept;
    void setIntroductionToNull() noexcept;

    /**  For column website  */
    ///Get the value of the column website, returns the default value if the column is null
    const std::string &getValueOfWebsite() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getWebsite() const noexcept;
    ///Set the value of the column website
    void setWebsite(const std::string &pWebsite) noexcept;
    void setWebsite(std::string &&pWebsite) noexcept;
    void setWebsiteToNull() noexcept;

    /**  For column twitter  */
    ///Get the value of the column twitter, returns the default value if the column is null
    const std::string &getValueOfTwitter() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTwitter() const noexcept;
    ///Set the value of the column twitter
    void setTwitter(const std::string &pTwitter) noexcept;
    void setTwitter(std::string &&pTwitter) noexcept;
    void setTwitterToNull() noexcept;

    /**  For column telegram  */
    ///Get the value of the column telegram, returns the default value if the column is null
    const std::string &getValueOfTelegram() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTelegram() const noexcept;
    ///Set the value of the column telegram
    void setTelegram(const std::string &pTelegram) noexcept;
    void setTelegram(std::string &&pTelegram) noexcept;
    void setTelegramToNull() noexcept;

    /**  For column nick_name  */
    ///Get the value of the column nick_name, returns the default value if the column is null
    const std::string &getValueOfNickName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getNickName() const noexcept;
    ///Set the value of the column nick_name
    void setNickName(const std::string &pNickName) noexcept;
    void setNickName(std::string &&pNickName) noexcept;
    void setNickNameToNull() noexcept;

    /**  For column referrer_uid  */
    ///Get the value of the column referrer_uid, returns the default value if the column is null
    const int64_t &getValueOfReferrerUid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getReferrerUid() const noexcept;
    ///Set the value of the column referrer_uid
    void setReferrerUid(const int64_t &pReferrerUid) noexcept;
    void setReferrerUidToNull() noexcept;

    /**  For column wallet_address  */
    ///Get the value of the column wallet_address, returns the default value if the column is null
    const std::string &getValueOfWalletAddress() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getWalletAddress() const noexcept;
    ///Set the value of the column wallet_address
    void setWalletAddress(const std::string &pWalletAddress) noexcept;
    void setWalletAddress(std::string &&pWalletAddress) noexcept;
    void setWalletAddressToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 15;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<UserInfo>;
    friend drogon::orm::BaseBuilder<UserInfo, true, true>;
    friend drogon::orm::BaseBuilder<UserInfo, true, false>;
    friend drogon::orm::BaseBuilder<UserInfo, false, true>;
    friend drogon::orm::BaseBuilder<UserInfo, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<UserInfo>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<std::string> email_;
    std::shared_ptr<std::string> avatar_;
    std::shared_ptr<::trantor::Date> createTs_;
    std::shared_ptr<::trantor::Date> updateTs_;
    std::shared_ptr<std::string> loginSource_;
    std::shared_ptr<std::string> walletToken_;
    std::shared_ptr<std::string> bannerImg_;
    std::shared_ptr<std::string> introduction_;
    std::shared_ptr<std::string> website_;
    std::shared_ptr<std::string> twitter_;
    std::shared_ptr<std::string> telegram_;
    std::shared_ptr<std::string> nickName_;
    std::shared_ptr<int64_t> referrerUid_;
    std::shared_ptr<std::string> walletAddress_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[15]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "email,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "avatar,";
            ++parametersCount;
        }
        sql += "create_ts,";
        ++parametersCount;
        if(!dirtyFlag_[3])
        {
            needSelection=true;
        }
        sql += "update_ts,";
        ++parametersCount;
        if(!dirtyFlag_[4])
        {
            needSelection=true;
        }
        if(dirtyFlag_[5])
        {
            sql += "login_source,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "wallet_token,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "banner_img,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "introduction,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "website,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "twitter,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "telegram,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "nick_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "referrer_uid,";
            ++parametersCount;
        }
        if(dirtyFlag_[14])
        {
            sql += "wallet_address,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[14])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace domain_new
} // namespace drogon_model
