/**
 *
 *  UserInfo.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UserInfo.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::domain_new;

const std::string UserInfo::Cols::_id = "\"id\"";
const std::string UserInfo::Cols::_email = "\"email\"";
const std::string UserInfo::Cols::_avatar = "\"avatar\"";
const std::string UserInfo::Cols::_create_ts = "\"create_ts\"";
const std::string UserInfo::Cols::_update_ts = "\"update_ts\"";
const std::string UserInfo::Cols::_login_source = "\"login_source\"";
const std::string UserInfo::Cols::_wallet_token = "\"wallet_token\"";
const std::string UserInfo::Cols::_banner_img = "\"banner_img\"";
const std::string UserInfo::Cols::_introduction = "\"introduction\"";
const std::string UserInfo::Cols::_website = "\"website\"";
const std::string UserInfo::Cols::_twitter = "\"twitter\"";
const std::string UserInfo::Cols::_telegram = "\"telegram\"";
const std::string UserInfo::Cols::_nick_name = "\"nick_name\"";
const std::string UserInfo::Cols::_referrer_uid = "\"referrer_uid\"";
const std::string UserInfo::Cols::_wallet_address = "\"wallet_address\"";
const std::string UserInfo::primaryKeyName = "id";
const bool UserInfo::hasPrimaryKey = true;
const std::string UserInfo::tableName = "\"user_info\"";

const std::vector<typename UserInfo::MetaData> UserInfo::metaData_={
{"id","int64_t","bigint",8,0,1,1},
{"email","std::string","character varying",255,0,0,0},
{"avatar","std::string","text",0,0,0,0},
{"create_ts","::trantor::Date","timestamp without time zone",0,0,0,0},
{"update_ts","::trantor::Date","timestamp without time zone",0,0,0,0},
{"login_source","std::string","character varying",32,0,0,1},
{"wallet_token","std::string","character varying",32,0,0,0},
{"banner_img","std::string","text",0,0,0,0},
{"introduction","std::string","character varying",1024,0,0,0},
{"website","std::string","character varying",1024,0,0,0},
{"twitter","std::string","character varying",1024,0,0,0},
{"telegram","std::string","character varying",1024,0,0,0},
{"nick_name","std::string","character varying",64,0,0,0},
{"referrer_uid","int64_t","bigint",8,0,0,0},
{"wallet_address","std::string","character varying",255,0,0,0}
};
const std::string &UserInfo::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UserInfo::UserInfo(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["email"].isNull())
        {
            email_=std::make_shared<std::string>(r["email"].as<std::string>());
        }
        if(!r["avatar"].isNull())
        {
            avatar_=std::make_shared<std::string>(r["avatar"].as<std::string>());
        }
        if(!r["create_ts"].isNull())
        {
            auto timeStr = r["create_ts"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["update_ts"].isNull())
        {
            auto timeStr = r["update_ts"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["login_source"].isNull())
        {
            loginSource_=std::make_shared<std::string>(r["login_source"].as<std::string>());
        }
        if(!r["wallet_token"].isNull())
        {
            walletToken_=std::make_shared<std::string>(r["wallet_token"].as<std::string>());
        }
        if(!r["banner_img"].isNull())
        {
            bannerImg_=std::make_shared<std::string>(r["banner_img"].as<std::string>());
        }
        if(!r["introduction"].isNull())
        {
            introduction_=std::make_shared<std::string>(r["introduction"].as<std::string>());
        }
        if(!r["website"].isNull())
        {
            website_=std::make_shared<std::string>(r["website"].as<std::string>());
        }
        if(!r["twitter"].isNull())
        {
            twitter_=std::make_shared<std::string>(r["twitter"].as<std::string>());
        }
        if(!r["telegram"].isNull())
        {
            telegram_=std::make_shared<std::string>(r["telegram"].as<std::string>());
        }
        if(!r["nick_name"].isNull())
        {
            nickName_=std::make_shared<std::string>(r["nick_name"].as<std::string>());
        }
        if(!r["referrer_uid"].isNull())
        {
            referrerUid_=std::make_shared<int64_t>(r["referrer_uid"].as<int64_t>());
        }
        if(!r["wallet_address"].isNull())
        {
            walletAddress_=std::make_shared<std::string>(r["wallet_address"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 15 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            email_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            avatar_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            loginSource_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            walletToken_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            bannerImg_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            introduction_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            website_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            twitter_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            telegram_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            nickName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            referrerUid_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            walletAddress_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

UserInfo::UserInfo(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            avatar_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            loginSource_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            walletToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            bannerImg_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            introduction_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            website_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            twitter_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            telegram_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            nickName_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            referrerUid_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            walletAddress_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
}

UserInfo::UserInfo(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("avatar"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["avatar"].isNull())
        {
            avatar_=std::make_shared<std::string>(pJson["avatar"].asString());
        }
    }
    if(pJson.isMember("create_ts"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["create_ts"].isNull())
        {
            auto timeStr = pJson["create_ts"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("update_ts"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["update_ts"].isNull())
        {
            auto timeStr = pJson["update_ts"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("login_source"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["login_source"].isNull())
        {
            loginSource_=std::make_shared<std::string>(pJson["login_source"].asString());
        }
    }
    if(pJson.isMember("wallet_token"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["wallet_token"].isNull())
        {
            walletToken_=std::make_shared<std::string>(pJson["wallet_token"].asString());
        }
    }
    if(pJson.isMember("banner_img"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["banner_img"].isNull())
        {
            bannerImg_=std::make_shared<std::string>(pJson["banner_img"].asString());
        }
    }
    if(pJson.isMember("introduction"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["introduction"].isNull())
        {
            introduction_=std::make_shared<std::string>(pJson["introduction"].asString());
        }
    }
    if(pJson.isMember("website"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["website"].isNull())
        {
            website_=std::make_shared<std::string>(pJson["website"].asString());
        }
    }
    if(pJson.isMember("twitter"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["twitter"].isNull())
        {
            twitter_=std::make_shared<std::string>(pJson["twitter"].asString());
        }
    }
    if(pJson.isMember("telegram"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["telegram"].isNull())
        {
            telegram_=std::make_shared<std::string>(pJson["telegram"].asString());
        }
    }
    if(pJson.isMember("nick_name"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["nick_name"].isNull())
        {
            nickName_=std::make_shared<std::string>(pJson["nick_name"].asString());
        }
    }
    if(pJson.isMember("referrer_uid"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["referrer_uid"].isNull())
        {
            referrerUid_=std::make_shared<int64_t>((int64_t)pJson["referrer_uid"].asInt64());
        }
    }
    if(pJson.isMember("wallet_address"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["wallet_address"].isNull())
        {
            walletAddress_=std::make_shared<std::string>(pJson["wallet_address"].asString());
        }
    }
}

void UserInfo::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            avatar_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            loginSource_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            walletToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            bannerImg_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            introduction_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            website_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            twitter_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            telegram_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            nickName_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            referrerUid_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            walletAddress_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
}

void UserInfo::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("avatar"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["avatar"].isNull())
        {
            avatar_=std::make_shared<std::string>(pJson["avatar"].asString());
        }
    }
    if(pJson.isMember("create_ts"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["create_ts"].isNull())
        {
            auto timeStr = pJson["create_ts"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("update_ts"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["update_ts"].isNull())
        {
            auto timeStr = pJson["update_ts"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTs_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("login_source"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["login_source"].isNull())
        {
            loginSource_=std::make_shared<std::string>(pJson["login_source"].asString());
        }
    }
    if(pJson.isMember("wallet_token"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["wallet_token"].isNull())
        {
            walletToken_=std::make_shared<std::string>(pJson["wallet_token"].asString());
        }
    }
    if(pJson.isMember("banner_img"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["banner_img"].isNull())
        {
            bannerImg_=std::make_shared<std::string>(pJson["banner_img"].asString());
        }
    }
    if(pJson.isMember("introduction"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["introduction"].isNull())
        {
            introduction_=std::make_shared<std::string>(pJson["introduction"].asString());
        }
    }
    if(pJson.isMember("website"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["website"].isNull())
        {
            website_=std::make_shared<std::string>(pJson["website"].asString());
        }
    }
    if(pJson.isMember("twitter"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["twitter"].isNull())
        {
            twitter_=std::make_shared<std::string>(pJson["twitter"].asString());
        }
    }
    if(pJson.isMember("telegram"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["telegram"].isNull())
        {
            telegram_=std::make_shared<std::string>(pJson["telegram"].asString());
        }
    }
    if(pJson.isMember("nick_name"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["nick_name"].isNull())
        {
            nickName_=std::make_shared<std::string>(pJson["nick_name"].asString());
        }
    }
    if(pJson.isMember("referrer_uid"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["referrer_uid"].isNull())
        {
            referrerUid_=std::make_shared<int64_t>((int64_t)pJson["referrer_uid"].asInt64());
        }
    }
    if(pJson.isMember("wallet_address"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["wallet_address"].isNull())
        {
            walletAddress_=std::make_shared<std::string>(pJson["wallet_address"].asString());
        }
    }
}

const int64_t &UserInfo::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UserInfo::getId() const noexcept
{
    return id_;
}
void UserInfo::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename UserInfo::PrimaryKeyType & UserInfo::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &UserInfo::getValueOfEmail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(email_)
        return *email_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getEmail() const noexcept
{
    return email_;
}
void UserInfo::setEmail(const std::string &pEmail) noexcept
{
    email_ = std::make_shared<std::string>(pEmail);
    dirtyFlag_[1] = true;
}
void UserInfo::setEmail(std::string &&pEmail) noexcept
{
    email_ = std::make_shared<std::string>(std::move(pEmail));
    dirtyFlag_[1] = true;
}
void UserInfo::setEmailToNull() noexcept
{
    email_.reset();
    dirtyFlag_[1] = true;
}

const std::string &UserInfo::getValueOfAvatar() const noexcept
{
    static const std::string defaultValue = std::string();
    if(avatar_)
        return *avatar_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getAvatar() const noexcept
{
    return avatar_;
}
void UserInfo::setAvatar(const std::string &pAvatar) noexcept
{
    avatar_ = std::make_shared<std::string>(pAvatar);
    dirtyFlag_[2] = true;
}
void UserInfo::setAvatar(std::string &&pAvatar) noexcept
{
    avatar_ = std::make_shared<std::string>(std::move(pAvatar));
    dirtyFlag_[2] = true;
}
void UserInfo::setAvatarToNull() noexcept
{
    avatar_.reset();
    dirtyFlag_[2] = true;
}

const ::trantor::Date &UserInfo::getValueOfCreateTs() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createTs_)
        return *createTs_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserInfo::getCreateTs() const noexcept
{
    return createTs_;
}
void UserInfo::setCreateTs(const ::trantor::Date &pCreateTs) noexcept
{
    createTs_ = std::make_shared<::trantor::Date>(pCreateTs);
    dirtyFlag_[3] = true;
}
void UserInfo::setCreateTsToNull() noexcept
{
    createTs_.reset();
    dirtyFlag_[3] = true;
}

const ::trantor::Date &UserInfo::getValueOfUpdateTs() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updateTs_)
        return *updateTs_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserInfo::getUpdateTs() const noexcept
{
    return updateTs_;
}
void UserInfo::setUpdateTs(const ::trantor::Date &pUpdateTs) noexcept
{
    updateTs_ = std::make_shared<::trantor::Date>(pUpdateTs);
    dirtyFlag_[4] = true;
}
void UserInfo::setUpdateTsToNull() noexcept
{
    updateTs_.reset();
    dirtyFlag_[4] = true;
}

const std::string &UserInfo::getValueOfLoginSource() const noexcept
{
    static const std::string defaultValue = std::string();
    if(loginSource_)
        return *loginSource_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getLoginSource() const noexcept
{
    return loginSource_;
}
void UserInfo::setLoginSource(const std::string &pLoginSource) noexcept
{
    loginSource_ = std::make_shared<std::string>(pLoginSource);
    dirtyFlag_[5] = true;
}
void UserInfo::setLoginSource(std::string &&pLoginSource) noexcept
{
    loginSource_ = std::make_shared<std::string>(std::move(pLoginSource));
    dirtyFlag_[5] = true;
}

const std::string &UserInfo::getValueOfWalletToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(walletToken_)
        return *walletToken_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getWalletToken() const noexcept
{
    return walletToken_;
}
void UserInfo::setWalletToken(const std::string &pWalletToken) noexcept
{
    walletToken_ = std::make_shared<std::string>(pWalletToken);
    dirtyFlag_[6] = true;
}
void UserInfo::setWalletToken(std::string &&pWalletToken) noexcept
{
    walletToken_ = std::make_shared<std::string>(std::move(pWalletToken));
    dirtyFlag_[6] = true;
}
void UserInfo::setWalletTokenToNull() noexcept
{
    walletToken_.reset();
    dirtyFlag_[6] = true;
}

const std::string &UserInfo::getValueOfBannerImg() const noexcept
{
    static const std::string defaultValue = std::string();
    if(bannerImg_)
        return *bannerImg_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getBannerImg() const noexcept
{
    return bannerImg_;
}
void UserInfo::setBannerImg(const std::string &pBannerImg) noexcept
{
    bannerImg_ = std::make_shared<std::string>(pBannerImg);
    dirtyFlag_[7] = true;
}
void UserInfo::setBannerImg(std::string &&pBannerImg) noexcept
{
    bannerImg_ = std::make_shared<std::string>(std::move(pBannerImg));
    dirtyFlag_[7] = true;
}
void UserInfo::setBannerImgToNull() noexcept
{
    bannerImg_.reset();
    dirtyFlag_[7] = true;
}

const std::string &UserInfo::getValueOfIntroduction() const noexcept
{
    static const std::string defaultValue = std::string();
    if(introduction_)
        return *introduction_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getIntroduction() const noexcept
{
    return introduction_;
}
void UserInfo::setIntroduction(const std::string &pIntroduction) noexcept
{
    introduction_ = std::make_shared<std::string>(pIntroduction);
    dirtyFlag_[8] = true;
}
void UserInfo::setIntroduction(std::string &&pIntroduction) noexcept
{
    introduction_ = std::make_shared<std::string>(std::move(pIntroduction));
    dirtyFlag_[8] = true;
}
void UserInfo::setIntroductionToNull() noexcept
{
    introduction_.reset();
    dirtyFlag_[8] = true;
}

const std::string &UserInfo::getValueOfWebsite() const noexcept
{
    static const std::string defaultValue = std::string();
    if(website_)
        return *website_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getWebsite() const noexcept
{
    return website_;
}
void UserInfo::setWebsite(const std::string &pWebsite) noexcept
{
    website_ = std::make_shared<std::string>(pWebsite);
    dirtyFlag_[9] = true;
}
void UserInfo::setWebsite(std::string &&pWebsite) noexcept
{
    website_ = std::make_shared<std::string>(std::move(pWebsite));
    dirtyFlag_[9] = true;
}
void UserInfo::setWebsiteToNull() noexcept
{
    website_.reset();
    dirtyFlag_[9] = true;
}

const std::string &UserInfo::getValueOfTwitter() const noexcept
{
    static const std::string defaultValue = std::string();
    if(twitter_)
        return *twitter_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getTwitter() const noexcept
{
    return twitter_;
}
void UserInfo::setTwitter(const std::string &pTwitter) noexcept
{
    twitter_ = std::make_shared<std::string>(pTwitter);
    dirtyFlag_[10] = true;
}
void UserInfo::setTwitter(std::string &&pTwitter) noexcept
{
    twitter_ = std::make_shared<std::string>(std::move(pTwitter));
    dirtyFlag_[10] = true;
}
void UserInfo::setTwitterToNull() noexcept
{
    twitter_.reset();
    dirtyFlag_[10] = true;
}

const std::string &UserInfo::getValueOfTelegram() const noexcept
{
    static const std::string defaultValue = std::string();
    if(telegram_)
        return *telegram_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getTelegram() const noexcept
{
    return telegram_;
}
void UserInfo::setTelegram(const std::string &pTelegram) noexcept
{
    telegram_ = std::make_shared<std::string>(pTelegram);
    dirtyFlag_[11] = true;
}
void UserInfo::setTelegram(std::string &&pTelegram) noexcept
{
    telegram_ = std::make_shared<std::string>(std::move(pTelegram));
    dirtyFlag_[11] = true;
}
void UserInfo::setTelegramToNull() noexcept
{
    telegram_.reset();
    dirtyFlag_[11] = true;
}

const std::string &UserInfo::getValueOfNickName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(nickName_)
        return *nickName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getNickName() const noexcept
{
    return nickName_;
}
void UserInfo::setNickName(const std::string &pNickName) noexcept
{
    nickName_ = std::make_shared<std::string>(pNickName);
    dirtyFlag_[12] = true;
}
void UserInfo::setNickName(std::string &&pNickName) noexcept
{
    nickName_ = std::make_shared<std::string>(std::move(pNickName));
    dirtyFlag_[12] = true;
}
void UserInfo::setNickNameToNull() noexcept
{
    nickName_.reset();
    dirtyFlag_[12] = true;
}

const int64_t &UserInfo::getValueOfReferrerUid() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(referrerUid_)
        return *referrerUid_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UserInfo::getReferrerUid() const noexcept
{
    return referrerUid_;
}
void UserInfo::setReferrerUid(const int64_t &pReferrerUid) noexcept
{
    referrerUid_ = std::make_shared<int64_t>(pReferrerUid);
    dirtyFlag_[13] = true;
}
void UserInfo::setReferrerUidToNull() noexcept
{
    referrerUid_.reset();
    dirtyFlag_[13] = true;
}

const std::string &UserInfo::getValueOfWalletAddress() const noexcept
{
    static const std::string defaultValue = std::string();
    if(walletAddress_)
        return *walletAddress_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserInfo::getWalletAddress() const noexcept
{
    return walletAddress_;
}
void UserInfo::setWalletAddress(const std::string &pWalletAddress) noexcept
{
    walletAddress_ = std::make_shared<std::string>(pWalletAddress);
    dirtyFlag_[14] = true;
}
void UserInfo::setWalletAddress(std::string &&pWalletAddress) noexcept
{
    walletAddress_ = std::make_shared<std::string>(std::move(pWalletAddress));
    dirtyFlag_[14] = true;
}
void UserInfo::setWalletAddressToNull() noexcept
{
    walletAddress_.reset();
    dirtyFlag_[14] = true;
}

void UserInfo::updateId(const uint64_t id)
{
}

const std::vector<std::string> &UserInfo::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "email",
        "avatar",
        "create_ts",
        "update_ts",
        "login_source",
        "wallet_token",
        "banner_img",
        "introduction",
        "website",
        "twitter",
        "telegram",
        "nick_name",
        "referrer_uid",
        "wallet_address"
    };
    return inCols;
}

void UserInfo::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAvatar())
        {
            binder << getValueOfAvatar();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCreateTs())
        {
            binder << getValueOfCreateTs();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUpdateTs())
        {
            binder << getValueOfUpdateTs();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLoginSource())
        {
            binder << getValueOfLoginSource();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getWalletToken())
        {
            binder << getValueOfWalletToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getBannerImg())
        {
            binder << getValueOfBannerImg();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIntroduction())
        {
            binder << getValueOfIntroduction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getWebsite())
        {
            binder << getValueOfWebsite();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getTwitter())
        {
            binder << getValueOfTwitter();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getTelegram())
        {
            binder << getValueOfTelegram();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getNickName())
        {
            binder << getValueOfNickName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getReferrerUid())
        {
            binder << getValueOfReferrerUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getWalletAddress())
        {
            binder << getValueOfWalletAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UserInfo::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    return ret;
}

void UserInfo::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAvatar())
        {
            binder << getValueOfAvatar();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCreateTs())
        {
            binder << getValueOfCreateTs();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUpdateTs())
        {
            binder << getValueOfUpdateTs();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLoginSource())
        {
            binder << getValueOfLoginSource();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getWalletToken())
        {
            binder << getValueOfWalletToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getBannerImg())
        {
            binder << getValueOfBannerImg();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIntroduction())
        {
            binder << getValueOfIntroduction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getWebsite())
        {
            binder << getValueOfWebsite();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getTwitter())
        {
            binder << getValueOfTwitter();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getTelegram())
        {
            binder << getValueOfTelegram();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getNickName())
        {
            binder << getValueOfNickName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getReferrerUid())
        {
            binder << getValueOfReferrerUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getWalletAddress())
        {
            binder << getValueOfWalletAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UserInfo::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getAvatar())
    {
        ret["avatar"]=getValueOfAvatar();
    }
    else
    {
        ret["avatar"]=Json::Value();
    }
    if(getCreateTs())
    {
        ret["create_ts"]=getCreateTs()->toDbStringLocal();
    }
    else
    {
        ret["create_ts"]=Json::Value();
    }
    if(getUpdateTs())
    {
        ret["update_ts"]=getUpdateTs()->toDbStringLocal();
    }
    else
    {
        ret["update_ts"]=Json::Value();
    }
    if(getLoginSource())
    {
        ret["login_source"]=getValueOfLoginSource();
    }
    else
    {
        ret["login_source"]=Json::Value();
    }
    if(getWalletToken())
    {
        ret["wallet_token"]=getValueOfWalletToken();
    }
    else
    {
        ret["wallet_token"]=Json::Value();
    }
    if(getBannerImg())
    {
        ret["banner_img"]=getValueOfBannerImg();
    }
    else
    {
        ret["banner_img"]=Json::Value();
    }
    if(getIntroduction())
    {
        ret["introduction"]=getValueOfIntroduction();
    }
    else
    {
        ret["introduction"]=Json::Value();
    }
    if(getWebsite())
    {
        ret["website"]=getValueOfWebsite();
    }
    else
    {
        ret["website"]=Json::Value();
    }
    if(getTwitter())
    {
        ret["twitter"]=getValueOfTwitter();
    }
    else
    {
        ret["twitter"]=Json::Value();
    }
    if(getTelegram())
    {
        ret["telegram"]=getValueOfTelegram();
    }
    else
    {
        ret["telegram"]=Json::Value();
    }
    if(getNickName())
    {
        ret["nick_name"]=getValueOfNickName();
    }
    else
    {
        ret["nick_name"]=Json::Value();
    }
    if(getReferrerUid())
    {
        ret["referrer_uid"]=(Json::Int64)getValueOfReferrerUid();
    }
    else
    {
        ret["referrer_uid"]=Json::Value();
    }
    if(getWalletAddress())
    {
        ret["wallet_address"]=getValueOfWalletAddress();
    }
    else
    {
        ret["wallet_address"]=Json::Value();
    }
    return ret;
}

Json::Value UserInfo::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 15)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getEmail())
            {
                ret[pMasqueradingVector[1]]=getValueOfEmail();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAvatar())
            {
                ret[pMasqueradingVector[2]]=getValueOfAvatar();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCreateTs())
            {
                ret[pMasqueradingVector[3]]=getCreateTs()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getUpdateTs())
            {
                ret[pMasqueradingVector[4]]=getUpdateTs()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getLoginSource())
            {
                ret[pMasqueradingVector[5]]=getValueOfLoginSource();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getWalletToken())
            {
                ret[pMasqueradingVector[6]]=getValueOfWalletToken();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getBannerImg())
            {
                ret[pMasqueradingVector[7]]=getValueOfBannerImg();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getIntroduction())
            {
                ret[pMasqueradingVector[8]]=getValueOfIntroduction();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getWebsite())
            {
                ret[pMasqueradingVector[9]]=getValueOfWebsite();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getTwitter())
            {
                ret[pMasqueradingVector[10]]=getValueOfTwitter();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getTelegram())
            {
                ret[pMasqueradingVector[11]]=getValueOfTelegram();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getNickName())
            {
                ret[pMasqueradingVector[12]]=getValueOfNickName();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getReferrerUid())
            {
                ret[pMasqueradingVector[13]]=(Json::Int64)getValueOfReferrerUid();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getWalletAddress())
            {
                ret[pMasqueradingVector[14]]=getValueOfWalletAddress();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getAvatar())
    {
        ret["avatar"]=getValueOfAvatar();
    }
    else
    {
        ret["avatar"]=Json::Value();
    }
    if(getCreateTs())
    {
        ret["create_ts"]=getCreateTs()->toDbStringLocal();
    }
    else
    {
        ret["create_ts"]=Json::Value();
    }
    if(getUpdateTs())
    {
        ret["update_ts"]=getUpdateTs()->toDbStringLocal();
    }
    else
    {
        ret["update_ts"]=Json::Value();
    }
    if(getLoginSource())
    {
        ret["login_source"]=getValueOfLoginSource();
    }
    else
    {
        ret["login_source"]=Json::Value();
    }
    if(getWalletToken())
    {
        ret["wallet_token"]=getValueOfWalletToken();
    }
    else
    {
        ret["wallet_token"]=Json::Value();
    }
    if(getBannerImg())
    {
        ret["banner_img"]=getValueOfBannerImg();
    }
    else
    {
        ret["banner_img"]=Json::Value();
    }
    if(getIntroduction())
    {
        ret["introduction"]=getValueOfIntroduction();
    }
    else
    {
        ret["introduction"]=Json::Value();
    }
    if(getWebsite())
    {
        ret["website"]=getValueOfWebsite();
    }
    else
    {
        ret["website"]=Json::Value();
    }
    if(getTwitter())
    {
        ret["twitter"]=getValueOfTwitter();
    }
    else
    {
        ret["twitter"]=Json::Value();
    }
    if(getTelegram())
    {
        ret["telegram"]=getValueOfTelegram();
    }
    else
    {
        ret["telegram"]=Json::Value();
    }
    if(getNickName())
    {
        ret["nick_name"]=getValueOfNickName();
    }
    else
    {
        ret["nick_name"]=Json::Value();
    }
    if(getReferrerUid())
    {
        ret["referrer_uid"]=(Json::Int64)getValueOfReferrerUid();
    }
    else
    {
        ret["referrer_uid"]=Json::Value();
    }
    if(getWalletAddress())
    {
        ret["wallet_address"]=getValueOfWalletAddress();
    }
    else
    {
        ret["wallet_address"]=Json::Value();
    }
    return ret;
}

bool UserInfo::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(1, "email", pJson["email"], err, true))
            return false;
    }
    if(pJson.isMember("avatar"))
    {
        if(!validJsonOfField(2, "avatar", pJson["avatar"], err, true))
            return false;
    }
    if(pJson.isMember("create_ts"))
    {
        if(!validJsonOfField(3, "create_ts", pJson["create_ts"], err, true))
            return false;
    }
    if(pJson.isMember("update_ts"))
    {
        if(!validJsonOfField(4, "update_ts", pJson["update_ts"], err, true))
            return false;
    }
    if(pJson.isMember("login_source"))
    {
        if(!validJsonOfField(5, "login_source", pJson["login_source"], err, true))
            return false;
    }
    else
    {
        err="The login_source column cannot be null";
        return false;
    }
    if(pJson.isMember("wallet_token"))
    {
        if(!validJsonOfField(6, "wallet_token", pJson["wallet_token"], err, true))
            return false;
    }
    if(pJson.isMember("banner_img"))
    {
        if(!validJsonOfField(7, "banner_img", pJson["banner_img"], err, true))
            return false;
    }
    if(pJson.isMember("introduction"))
    {
        if(!validJsonOfField(8, "introduction", pJson["introduction"], err, true))
            return false;
    }
    if(pJson.isMember("website"))
    {
        if(!validJsonOfField(9, "website", pJson["website"], err, true))
            return false;
    }
    if(pJson.isMember("twitter"))
    {
        if(!validJsonOfField(10, "twitter", pJson["twitter"], err, true))
            return false;
    }
    if(pJson.isMember("telegram"))
    {
        if(!validJsonOfField(11, "telegram", pJson["telegram"], err, true))
            return false;
    }
    if(pJson.isMember("nick_name"))
    {
        if(!validJsonOfField(12, "nick_name", pJson["nick_name"], err, true))
            return false;
    }
    if(pJson.isMember("referrer_uid"))
    {
        if(!validJsonOfField(13, "referrer_uid", pJson["referrer_uid"], err, true))
            return false;
    }
    if(pJson.isMember("wallet_address"))
    {
        if(!validJsonOfField(14, "wallet_address", pJson["wallet_address"], err, true))
            return false;
    }
    return true;
}
bool UserInfo::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserInfo::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(1, "email", pJson["email"], err, false))
            return false;
    }
    if(pJson.isMember("avatar"))
    {
        if(!validJsonOfField(2, "avatar", pJson["avatar"], err, false))
            return false;
    }
    if(pJson.isMember("create_ts"))
    {
        if(!validJsonOfField(3, "create_ts", pJson["create_ts"], err, false))
            return false;
    }
    if(pJson.isMember("update_ts"))
    {
        if(!validJsonOfField(4, "update_ts", pJson["update_ts"], err, false))
            return false;
    }
    if(pJson.isMember("login_source"))
    {
        if(!validJsonOfField(5, "login_source", pJson["login_source"], err, false))
            return false;
    }
    if(pJson.isMember("wallet_token"))
    {
        if(!validJsonOfField(6, "wallet_token", pJson["wallet_token"], err, false))
            return false;
    }
    if(pJson.isMember("banner_img"))
    {
        if(!validJsonOfField(7, "banner_img", pJson["banner_img"], err, false))
            return false;
    }
    if(pJson.isMember("introduction"))
    {
        if(!validJsonOfField(8, "introduction", pJson["introduction"], err, false))
            return false;
    }
    if(pJson.isMember("website"))
    {
        if(!validJsonOfField(9, "website", pJson["website"], err, false))
            return false;
    }
    if(pJson.isMember("twitter"))
    {
        if(!validJsonOfField(10, "twitter", pJson["twitter"], err, false))
            return false;
    }
    if(pJson.isMember("telegram"))
    {
        if(!validJsonOfField(11, "telegram", pJson["telegram"], err, false))
            return false;
    }
    if(pJson.isMember("nick_name"))
    {
        if(!validJsonOfField(12, "nick_name", pJson["nick_name"], err, false))
            return false;
    }
    if(pJson.isMember("referrer_uid"))
    {
        if(!validJsonOfField(13, "referrer_uid", pJson["referrer_uid"], err, false))
            return false;
    }
    if(pJson.isMember("wallet_address"))
    {
        if(!validJsonOfField(14, "wallet_address", pJson["wallet_address"], err, false))
            return false;
    }
    return true;
}
bool UserInfo::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserInfo::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }

            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 1024)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 1024)";
                return false;
            }

            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 1024)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 1024)";
                return false;
            }

            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 1024)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 1024)";
                return false;
            }

            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 1024)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 1024)";
                return false;
            }

            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }

            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
